In [1]:
import pandas as pd
import sqlite3
import requests
from bs4 import BeautifulSoup
from io import StringIO

# Metodo para solucionar el error unicode

# Codificar la URL correctamente
url = 'https://pokemon.fandom.com/es/wiki/Lista_de_Pokémon_de_la_primera_generación'
response = requests.get(url)

# Usar BeautifulSoup para analizar el contenido HTML
# 'html.parser' es el analizador HTML integrado a BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

# *** Convertir el HTML a un objeto StringIO ***
# StringIO: Convertimos el HTML completo en una cadena
html_string = str(soup)
# y luego lo envolvemos en un objeto StringIO.
html_io = StringIO(html_string)
# Esto simula un archivo HTML, permitiendo a pd.read_html leerlo adecuadamente.
# Leer las tablas del HTML usando StringIO
tables = pd.read_html(html_io)

# Conexion a base de datos
conn = sqlite3.connect('pokemon.db')

# Itera dentro de la pagina, imprime el indice y el dataframe (tabla) que encuentre
for index, table in enumerate(tables):
    print("**************************************************************")
    print("**************************************************************")
    print('Index', index)
    print('Tbl->Col', table)

**************************************************************
**************************************************************
Index 0
Tbl->Col                                                    0
0  Este artículo solo se refiere a la lista de lo...
**************************************************************
**************************************************************
Index 1
Tbl->Col        #  Mini sprite      Nombre    Tipo 1    Tipo 2 Japonés   Romanizado  \
0      1          NaN   Bulbasaur    Planta    Veneno   フシギダネ  Fushigidane
1      2          NaN     Ivysaur    Planta    Veneno   フシギソウ    Fushigisō
2      3          NaN    Venusaur    Planta    Veneno   フシギバナ  Fushigibana
3      4          NaN  Charmander     Fuego     Fuego    ヒトカゲ     Hitokage
4      5          NaN  Charmeleon     Fuego     Fuego    リザード       Rizādo
..   ...          ...         ...       ...       ...     ...          ...
146  147          NaN     Dratini    Dragón    Dragón   ミニリュウ      Miniryū
147  148          NaN   Dragonair    Dragón    Dragón   ハクリュー      Hakuryū
148  149          NaN   Dragonite    Dragón   Volador   カイリュー       Kairyū
149  150          NaN      Mewtwo  Psíquico  Psíquico   ミュウツー       Myūtsū
150  151          NaN         Mew  Psíquico  Psíquico     ミュウ          Myū

    Rom. oficial  G. hvo 1 G. hvo 2  JOH  HOE  SIN  TES1    KAL    ALO    GAL
0    Fushigidane  Monstruo   Planta  226  NaN  NaN   NaN  080CE    NaN    NaN
1     Fushigisou  Monstruo   Planta  227  NaN  NaN   NaN  081CE    NaN    NaN
2    Fushigibana  Monstruo   Planta  228  NaN  NaN   NaN  082CE    NaN    NaN
3       Hitokage  Monstruo   Dragón  229  NaN  NaN   NaN  083CE    NaN  378.0
4        Lizardo  Monstruo   Dragón  230  NaN  NaN   NaN  084CE    NaN  379.0
..           ...       ...      ...  ...  ...  ...   ...    ...    ...    ...
146      Miniryu    Agua 1   Dragón  241  NaN  NaN   NaN  145MO  281.0    NaN
147      Hakuryu    Agua 1   Dragón  242  NaN  NaN   NaN  146MO  282.0    NaN
148       Kairyu    Agua 1   Dragón  243  NaN  NaN   NaN  147MO  283.0    NaN
149       Mewtwo   Ninguno      NaN  249  NaN  NaN   NaN  151MO    NaN    NaN
150          Mew   Ninguno      NaN  250  NaN  NaN   NaN    NaN    NaN    NaN

[151 rows x 17 columns]
**************************************************************
**************************************************************
Index 2
Tbl->Col                       Clasificaciones de los Pokémon  \
                                         Por Pokédex
0  Pokédex Nacional Kanto (1ª gen.) Johto (2ª gen...

                                                      \
                                       Por atributos
0  Por tipos Por grupos huevo Por especie Por alt...

                                                      \
                                    Por estadísticas
0  Por estadísticas base Por ratio de captura Por...


                                          Miscelánea
0  Alfabéticamente Numéricamente Por generación P...

In [2]:
df = pd.DataFrame(tables[1])
df

,#,Mini sprite,Nombre,Tipo 1,Tipo 2,Japonés,Romanizado,Rom. oficial,G. hvo 1,G. hvo 2,JOH,HOE,SIN,TES1,KAL,ALO,GAL
0,1,NaN,Bulbasaur,Planta,Veneno,フシギダネ,Fushigidane,Fushigidane,Monstruo,Planta,226,NaN,NaN,NaN,080CE,NaN,NaN
1,2,NaN,Ivysaur,Planta,Veneno,フシギソウ,Fushigisō,Fushigisou,Monstruo,Planta,227,NaN,NaN,NaN,081CE,NaN,NaN
2,3,NaN,Venusaur,Planta,Veneno,フシギバナ,Fushigibana,Fushigibana,Monstruo,Planta,228,NaN,NaN,NaN,082CE,NaN,NaN
3,4,NaN,Charmander,Fuego,Fuego,ヒトカゲ,Hitokage,Hitokage,Monstruo,Dragón,229,NaN,NaN,NaN,083CE,NaN,378.0
4,5,NaN,Charmeleon,Fuego,Fuego,リザード,Rizādo,Lizardo,Monstruo,Dragón,230,NaN,NaN,NaN,084CE,NaN,379.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,NaN,Dratini,Dragón,Dragón,ミニリュウ,Miniryū,Miniryu,Agua 1,Dragón,241,NaN,NaN,NaN,145MO,281.0,NaN
147,148,NaN,Dragonair,Dragón,Dragón,ハクリュー,Hakuryū,Hakuryu,Agua 1,Dragón,242,NaN,NaN,NaN,146MO,282.0,NaN
148,149,NaN,Dragonite,Dragón,Volador,カイリュー,Kairyū,Kairyu,Agua 1,Dragón,243,NaN,NaN,NaN,147MO,283.0,NaN
149,150,NaN,Mewtwo,Psíquico,Psíquico,ミュウツー,Myūtsū,Mewtwo,Ninguno,NaN,249,NaN,NaN,NaN,151MO,NaN,NaN
150,151,NaN,Mew,Psíquico,Psíquico,ミュウ,Myū,Mew,Ninguno,NaN,250,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
    try:
        #Select el index que deseamos
        table = tables[1]
        table_name = 'primera_generacion'
        # Exporto la tabla a sqlite
        table.to_sql(table_name, conn, if_exists='replace', index=False)

        print(f'Tabla {table_name} exportada a SQLite')
    except Exception as e:
        print(f'Error al exportar tabla {table_name}: {str(e)}')

conn.commit()
# Cierro conexion a la base de datos
conn.close()

Tabla primera_generacion exportada a SQLite